### PR TITLE
Add fastpath to table find.

### PR DESCRIPTION
**Pull request by andrewchambers**
I think this still needs benchmarking to prove it does anything useful.

### CODE REVIEW

**Comment by andrewchambers** [comment]
This implementation is the same as struct find, so I wonder if they could be combined.

**Comment by andrewchambers** [comment]
ehh,  actually this pr is broken because deleted gets decremented.

**Comment by bakpakin** [comment]
Yes, the invariant looks fine. deleted should always have the number of tombstone values in the table, so if it is zero we could fast track. However, I wonder if the micro-optimization is actually worth it. I suspect the improvement will be almost zero.

**Comment by andrewchambers** [comment]
tab.janet
```
(def t @{})
(for i 0 10000
  (put t i i))
(for i 0 20000
  (get t i))
```

```
[ac@black:~/src/janet]$ valgrind --tool=callgrind ./janet-slow ./tab.janet 
==84021== Callgrind, a call-graph generating cache profiler
==84021== Copyright (C) 2002-2017, and GNU GPL'd, by Josef Weidendorfer et al.
==84021== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==84021== Command: ./janet-slow ./tab.janet
==84021== 
==84021== For interactive control, run 'callgrind_control -h'.
==84021== 
==84021== Events    : Ir
==84021== Collected : 312675345
==84021== 
==84021== I   refs:      312,675,345

[ac@black:~/src/janet]$ valgrind --tool=callgrind ./janet-fast ./tab.janet 
==84022== Callgrind, a call-graph generating cache profiler
==84022== Copyright (C) 2002-2017, and GNU GPL'd, by Josef Weidendorfer et al.
==84022== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==84022== Command: ./janet-fast ./tab.janet
==84022== 
==84022== For interactive control, run 'callgrind_control -h'.
==84022== 
==84022== Events    : Ir
==84022== Collected : 312413487
==84022== 
==84022== I   refs:      312,413,487

```

**Pull request closed without merging**
