### PR TITLE
moved error handling in ev/call

### PR DESCRIPTION
**Pull request by Saikyun**
fix for https://github.com/janet-lang/janet/issues/509

### CODE REVIEW

**Comment by Saikyun** [comment]
Sadly don't know what causes the windows error, and can't test myself on windows atm. If you know what's wrong, feel free to either tell me what to do, or just make your own solution and ignore this PR. :)

**Comment by pepe** [comment]
I think @bakpakin mentioned, that windows net code is not that stable yet.

**Review by pepe — APPROVED** [review]
LGTM. It makes a sense to check for NULL before accessing members of the fiber.

**Comment by bakpakin** [comment]
Good catch, I fixed this before checking this issue when I saw CI failing, but that is indeed the fix.

**Pull request closed without merging**
