### PR TITLE
Update ev.c to use the new binding style that provides source information

### PR DESCRIPTION
**Pull request by yumaikas**
Update ev.c based on #720

### CODE REVIEW

**Comment by yumaikas** [comment]
https://lgtm.com/projects/g/janet-lang/janet/logs/rev/pr-f2aec906aedc1c53032e71c67f37a39b37ca55d3/lang:cpp/stage:Build%20merge_b08a16e375cf0148e24e3d5e1bad87d4116d765c

Looks like the new macro declares things differently than they are in `janet.h`?

**Comment by pepe** [comment]
It looks like `ev/take` doc was copied from `ev/give` in your version

**Comment by bakpakin** [comment]
Missing ev/rselect, which I think is what is causing the LGTM error.

**Comment by yumaikas** [comment]
So, ev/reselect was added, and the errors are still happening.

**Comment by yumaikas** [comment]
LGTM checks are passing now, and this is a closer match to what was being done before

**Pull request merged**
