### PR TITLE
Minor fixes for parser.

### PR DESCRIPTION
**Pull request by andrewchambers**
Check length before dereferencing buffer in tokenchar.
Check keywords are valid utf-8.
Fix minor typos.

### CODE REVIEW

**Comment by bakpakin** [comment]
Looks good. However, I don’t think there is a need to check for the empty symbol in the parser. How could that possibly be triggered?

**Comment by andrewchambers** [comment]
Yeah, I had wondered if it was just dead code.

**Comment by bakpakin** [comment]
Yeah, I think it was just dead code. By checking if the first character is a colon, we are assuming length > 0. This makes sense, as some character needs to be read to get the parser to this state.

**Comment by bakpakin** [comment]
Otherwise, utf-8 checking looks good. Please remove the old, dead code and adding a test case for parsing invalid utf-8 in a keyword in one of the test suites would be great.

**Comment by andrewchambers** [comment]
Cool, will do.

**Comment by andrewchambers** [comment]
Added the tests.

**Comment by bakpakin** [comment]
Solid, thanks!

**Pull request merged**
