### PR TITLE
Update math.c for the new style

### PR DESCRIPTION
**Pull request by yumaikas**
Part of the #720 effort

### CODE REVIEW

**Comment by yumaikas** [comment]
I did update some of the docs as I went, making "Returns" used consistently, switching to "the natural logarithm of x", as well as adding small macro for when math constants were defined.

**Comment by bakpakin** [comment]
Looks good. I think we can remove all reference  to the JDOC macro now though, which I will delete after we finish this porting process. The bootstrapping special handling has been moved into the JANET_CORE_* macros.

**Comment by yumaikas** [comment]
So, my C-macro-fu isn't up to the task right now. I'll try to come back to this in a couple days if someone else doesn't get something written up for it, but I want to make sure that we have a macro for defining constants, rather than just defining a macro in math.c that might not follow the bootstrapping process.

**Comment by bakpakin** [comment]
Thanks, the JANET_DEF macros look good as well.

**Comment by yumaikas** [comment]
Fixed the merge conflicts with the ev.c changes

**Pull request merged**
