### PR TITLE
Add Wix/msi installer for Windows

### PR DESCRIPTION
**Pull request by leafgarland**
As discussed in #397, here is a new installer for Windows using Wix. So far it has not shown the hanging issue we have seen with the NSIS one when doing silent installs.

It builds x86/x64 specific installers that can be installed per-user or per-machine. The default is per-user. If you select per-machine then you can also customize the install location.

image
image
image
I would prefer to get rid of the above feature selection step but it requires a lot of customisations in Wix and getting this far was way more trouble than I wanted.
image

The custom images in the dialogs were made with [ronin](https://100r.co/site/ronin.html), if anybody wants to make better ones

```
(resize 493 58)

(clear)

(fill frame 
  (gradient 
    (line 0 0 493 0) 
    ("#09a5b8" "#076591")))

(import "icon_svg.svg" 
  (rect 422 2 70 56))
```

```
(clear)

(resize 493 312)

(fill 
  (rect 0 0 164 312) 
  (gradient 
    (line 0 0 0 493) 
    ("#09a5b8" "#076591")))

(import "janet-w200.png" 
  (rect 10 10 144 144))
```

### CODE REVIEW

**Comment by pepe** [comment]
Wow, that seems like a lot of troubles endured :-). Good work.

**Comment by sogaiu** [comment]
Looks nice!

**Comment by bakpakin** [comment]
Wow this is so much better! I had heard Wix was much harder to use than NSIS but the end result looks pretty nice and the source code actually looks not too bad at all. Thanks for taking this on, I wasted a lot of time fighting with NSIS and it’s strange scripting language.

**Comment by leafgarland** [comment]
Wix is not so bad but there is a lot of outdated and missing documentation/examples. I spent a lot of time pairing examples down to find out what was actually needed. I'm pretty pleased to have got it relatively succinct.

**Comment by andrewchambers** [comment]
Thank you, we really appreciate this.

**Pull request merged**
