### PR TITLE
Add file/{fdopen,fileno} functions.

### PR DESCRIPTION
**Pull request by andrewchambers**

### CODE REVIEW

**Comment by bakpakin** [comment]
Looks pretty good. However, windows docs say to use _fdopen and _fileno respectively. The non prefixed versions are deprecated.

**Comment by andrewchambers** [comment]
Those seemed to be windows C++ docs, but I wasn't sure. _fdopen didn't compile on my machine.

**Comment by bakpakin** [comment]
Yes, it will probably need an #ifdef JANET_WINDOWS

**Comment by andrewchambers** [comment]
fixed

**Comment by xigoi** [comment]
Why were these functions removed?

**Comment by sogaiu** [comment]
I don't know but for reference, here's the commit where they were removed: https://github.com/janet-lang/janet/commit/b8d530da36d01cfd8e5b05879bfb5a51d8a1ce05

**Comment by andrewchambers** [comment]
because they are useless without additional C functions to provide file descriptors.they don't make sense standalone.

**Pull request merged**
