### PR TITLE
Support Android (termux)

### PR DESCRIPTION
**Pull request by svercl**
This change allows compiling and running on Android in termux.

### CODE REVIEW

**Comment by sogaiu** [comment]
It built here and all tests passed.

**Comment by bradms** [comment]
I added it to the meson build as well. Tested on my device. One thing that needs to be changed is that the dep should only be added when `JANET_REDUCED_OS` is not defined.

**Comment by sogaiu** [comment]
After installing `ninja` and `meson` (using `pip3`) I tried out the modifications in 559fd70 with some success :)

**Comment by sogaiu** [comment]
I also had success via the `Makefile` route by installing the clang, binutils, make, git, and libandroid-spawn packages first.

**Comment by svercl** [comment]
Yes! I assumed those packages are installed already, but I think this should be mentioned for running in Termux.

**Comment by sogaiu** [comment]
Not sure where that info ought to go (may be in the [janet-lang.org repository](https://github.com/janet-lang/janet-lang.org)?).

For future folks, a copy-paste one-liner to install aforementioned packages might be:

```pkg install binutils clang git libandroid-spawn make```

**Pull request merged**
