### PR TITLE
Revert "Optimize nil conditions for while and if"

### LINKED ISSUE #1327: (default) not working
I don't know how to name the bug (issue title). It is very fundamental.

```
(def x "A")
#(default x "B")
(def x (if (= nil x) "B" x))
# this works
# (def x (if (pp (= nil x)) "B" x))
(pp x)
```

What I see as output: `B`
What I should see: `A`

### PR DESCRIPTION
**Pull request by iacore**
This seems to fix #1327 (the example in that issue works correctly now)

### CODE REVIEW

**Comment by sogaiu** [comment]
It worked here too (and the tests for `make test` passed as well).

**Comment by sogaiu** [comment]
Nice to have a regression test :+1:

**Comment by bakpakin** [comment]
Ideally we could keep the improvements from the original change without just blanket reverting them

**Comment by sogaiu** [comment]
@primo-ppcg Sorry to bug you (^^;

Do you happen to have some spare cycles to take a look at this?

**Comment by bakpakin** [comment]
I've got it covered.

The issue was with the constant conditional calculation. When `x` was constant in `(if (not= x nil) ...)` , the true and false code would be swapped.

**Comment by primo-ppcg** [comment]
> I've got it covered.

I apologize for the regression. The update https://github.com/janet-lang/janet/commit/56f33f514b4a29a449869ca2899f73d34b292ef7 will fail to optimize code like `(if (not= x nil) ...)` and will only optimize code like `(if (,not= x nil) ...)` within a macro, which is mildly unfortunate. This doesn't appear to have been the source of the error (but rather a failure to update previously existing logic), unless there's another issue with it that I'm unaware of.

**Comment by iacore** [comment]
`not=` in `(if (not= x nil) ...)` could mean something else, I think

**Pull request closed without merging**
