### PR TITLE
Use existing :ref array for redefined var bindings

### PR DESCRIPTION
**Pull request by pyrmont**
Currently, if you call `var` repeatedly, Janet will create a new binding that does not use the `:ref` value of the existing binding. This might be intentional but it is inconsistent with the way that `varfn` works. This PR uses the array that is associated with the `:ref` of the current binding.

Before PR:

```janet
(var a 1)
(defn inc1 [] (+ 1 a))
(inc1) # => 2
(var a 2)
(inc1) # => 2
```

After PR:

```janet
(var a 1)
(defn inc1 [] (+ 1 a))
(inc1) # => 2
(var a 2)
(inc1) # => 3
```

### CODE REVIEW

**Comment by andrewchambers** [comment]
does this work with locals?

**Comment by pyrmont** [comment]
@andrewchambers Not as currently implemented. I thought the primary scenario where someone is going to be surprised by the current behaviour is where the `var`s is in the top-level scope. So to address that (and to minimise the complexity of the change), this PR changes only the way top-level `var`s work.

In all honesty, I'm still unclear on how the `namelocal` function works so that was the other reason to keep away from it. But if we thought it were better to have `var`s work consistently at all scopes, I can look into making that change, too.

**Comment by saikyun** [comment]
Not sure if I'm doing something wrong, but I can't get it to work across files:

## Example 1

### Code

```
jona@wings-of-fire:~/programmering/test-redef$ cat uselul.janet
(spit "lul.janet" `(def a :dynamic 10) (print "1st a is: " a)`)

(import ./lul :as l :fresh true)

(defn b [] (+ l/a l/a))

(print "call 1: " (b))


(spit "lul.janet" `(def a :dynamic 1337) (print "2nd a is: " a)`)
(import ./lul :as l :fresh true)

(print "call 2: " (b))
```

### Execution

```
jona@wings-of-fire:~/programmering/test-redef$ janet uselul.janet 
1st a is: 10
call 1: 20
2nd a is: 1337
call 2: 20
```

## Example 2

### Code

```
jona@wings-of-fire:~/programmering/test-redef$ cat uselul2.janet 
(spit "lul.janet" `(def a :dynamic 10) (print "1st a is: " a)`)

(import ./lul :as l)

(defn b [] (+ l/a l/a))

(print "call 1: " (b))


(spit "lul.janet" `(def a :dynamic 1337) (print "2nd a is: " a)`)

(dofile "lul.janet")

(print "call 2: " (b))
```

### Execution

```
jona@wings-of-fire:~/programmering/test-redef$ janet uselul2.janet 
1st a is: 10
call 1: 20
2nd a is: 1337
call 2: 20
```

**Comment by bakpakin** [comment]
To be consistent with the behavior for `def`, this should probably only happen if `:redef` or whatever dyn is decided on is present and the changes in https://github.com/janet-lang/janet/pull/898 are merged. This definitely shouldn't work on locals and probably shouldn't be on by default since it could mess with macros (especially anaphoric macros) in unexpected ways.

**Comment by pyrmont** [comment]
@bakpakin Got it. Will update this to mirror the approach taken in the other PR once that's been decided and merged.

**Comment by saikyun** [comment]
I had some thoughts wrt the different "concepts" that are being considered
atm:
def / defn / defmacro
var / varfn
:redef-enabled def / defn / defmacro / var / varfn

The way I see it, `var` being both `:redef`able and not makes a lot of
sense, since sometimes you just want a new `var`, and sometimes you want to
redefine the existing one. However, for `varfn`, is there ever a situation
where this acts differently than a redefinable `defn`?

I was thinking that maybe one could clean the above up ever so slightly, by
removing `varfn` and thus only having:
def / defn / defmacro
var
:redef-enabled def / defn / defmacro / var

The reason being that for a newcomer, each extra "thing" is an extra thing
to learn, and if two concepts are essentially the same thing, it might be
hard to explain why they both exists. Also, while implementation wise `var`
and `varfn` are similar, I get the feeling that when using them they're
quite different. `var` is for mutatable state, while `varfn` is for
declaring functions or redefining them during runtime.

Den ons 5 jan. 2022 kl 04:24 skrev Michael Camilleri <
***@***.***>:

**Comment by bakpakin** [comment]
Yeah, the truth is that the :redef functionality on bindings actually deprecates varfn. Probably better to deprecate varfn and then remove it in a future version.

**Comment by andrewchambers** [comment]
I definitely feel that this risks making things quite muddy and complicated - we are quite blind to it because we have a good understanding of the current way symbols are resolved.

**Comment by pyrmont** [comment]
@bakpakin If we want to make a distinction between redefinable `var` bindings and ordinary `var` bindings, I think we'll have to make fundamental changes than are currently in this PR.

## Background

For discussion purposes, I'll briefly summarise things:

1. A Janet 'binding' is really a `JanetTable` that is associated with a symbol in an environment table.
2. Janet has five types of bindings:
   1. `JANET_BINDING_DEF`
   2. `JANET_BINDING_VAR`
   3. `JANET_BINDING_MACRO`
   4. `JANET_BINDING_DYNAMIC_DEF`
   5. `JANET_BINDING_DYNAMIC_MACRO`
3. There is no simple way to determine the type of a binding from the table itself. Instead Janet categorises a binding based on the follow characteristics:
   1. presence of `:macro` key
   2. presence of `:redef` key
   3. presence of `:value`/`:ref` key
   
   You can see this in action here:

   https://github.com/janet-lang/janet/blob/07ec89276baf66ac157108977a6201a3aa322149/src/core/util.c#L629-L647

## Problem

The problem is that there is no way to distinguish between a redefinable `def` binding (which has `:redef` and `:ref` keys) and a redefinable `var` binding (which would have `:redef` and `:ref` keys).

## Solutions

Assuming we do want redefinable `var` bindings, then it seems to me that the possible approaches are:

1. Add an additional metadata keyword to distinguish between `var` bindings and `def` bindings (similar to how `defmacro` bindings are distinguished by the presence of the `:macro` keyword). The keyword could be `:mutable`.

2. Store a redefinable `def` binding under a different key than `:ref`. We could store it under `:value`, for instance (which is the key used for non-redefinable `def` bindings). The presence of the `:redef` key would indicate whether the `def` binding is redefinable or not.

3. Make all `var` bindings redefinable.

**Comment by pyrmont** [comment]
I thought more about it and it just seemed simpler to go **`def` is `:value`** and **`var` is `:ref`**.

As a result, the latest commit implements Solution 2 to add `:redef` support to `var` bindings. You can see these now added to the test suite.

**Comment by bakpakin** [comment]
I'm going to agree with Andrew here, there is just too much extra complexity going on here. it might be easier to just have top level bar declarations re-use the reference array if a binding already exists

**Comment by pyrmont** [comment]
No worries. With the additions made in 5b5a7e5a243e9be0274a0df575d6e94c9da2b4ca, I'll close this PR. Can always revisit this in the future if necessary :)

**Pull request closed without merging**
