### PR TITLE
Implement polymorphic compare

### PR DESCRIPTION
**Pull request by MikeBeller**
Addresses issue #272 by implementing compare, compare<,compare= (etc.) functions.  Implements compare method for int/s64 and int/u64.  Removes vestigial comparison methods on int/s64 and int/u64.

### CODE REVIEW

**Comment by andrewchambers** [comment]
Great work.

**Comment by MikeBeller** [comment]
Thanks, @andrewchambers !

**Comment by MikeBeller** [comment]
That last commit was just to remove some dead code in the tests and a call to round that did nothing.  (Just cleanup.)

**Comment by bakpakin** [comment]
Looks good to me, merging.

**Pull request merged**
