### PR TITLE
Tweak get-in behavior

### PR DESCRIPTION
**Pull request by sogaiu**
An attempt to address https://github.com/janet-lang/janet/issues/751

### CODE REVIEW

**Review by pepe — COMMENTED** [review]
Just nitpicking but we can use `:until` modifier and condition without `not`.

**Comment by sogaiu** [comment]
I have no attachment to the current implementation in this PR :)

**Comment by pepe** [comment]
It actually does not matter, as the macro expansion of both implementations would probably be very similar.

**Review by pepe — APPROVED** [review]
LGTM

**Comment by bakpakin** [comment]
Lgtm

**Pull request merged**
