### PR TITLE
light markup in some docs in corelib

### PR DESCRIPTION
**Pull request by uvtc**
For #524

### CODE REVIEW

**Comment by sogaiu** [comment]
@uvtc What do you think of the idea of changing the argument in all four cases to be the same?

For `string` it's `parts`, whereas for the other three it's `xs`.

Also the docstring prose uses the word "Values".  It seems like that could be replaced with whatever the argument name ends up being (e.g. `xs`, `parts`, or `values`).

**Comment by uvtc** [comment]
My guess is that "xs" (or even "args") is a sort of "catch-all" for when you don't have a more descriptive word to use for the extra args.

For these cases, I think that "parts" (as used in the doc for `string`) is good, but "pieces" would be even better. (Parts makes me think of different parts that make up an engine, but pieces makes me think of (possibly disparate) items that we're stitching together to make the final thing).

If the docs are changed, will they become out of sync with some source code elsewhere?

**Comment by sogaiu** [comment]
Thanks for your latest attempt.

Regarding `parts` vs `pieces` -- to be honest I don't have similar associations.  I find `parts` slightly better because it's shorter :)  I think it may also have the advantage of being harder to mispell.

Of course, it's ultimately not up to me, but I'm also fine with using `xs` -- that seems to be used elsewhere and IIUC it's even used in code and docs in other programming languages.

Not sure about being out-of-sync with source -- actually, I don't quite follow what you mean.  Would you mind elaborating?

I did find there is at least one other use of `parts`:
```
   (array/concat arr & parts)

    Concatenates a variable number of arrays (and tuples) into the first
    argument which must be an array. If any of the parts are arrays or
    tuples, their elements will be inserted into the array. Otherwise,
    each part in parts will be appended to arr in order. Return the
    modified array arr.
```

**Comment by uvtc** [comment]
> Not sure about being out-of-sync with source -- actually, I don't quite follow what you mean. Would you mind elaborating?

As in, do the function params here in the docs need to match up with (stay in sync with) implementation elsewhere?

**Comment by sogaiu** [comment]
I confess I don't get how that could be an issue.

**Comment by uvtc** [comment]
Sorry, my C is very rusty... I was thinking maybe there was a C-function signature somewhere (which I'm unaware of) that the doc text was supposed to match up with. But it sounds like I'm off-base and that's not the case.

**Comment by sogaiu** [comment]
Thanks for explanation.

For reference, I've search across the janet repository and found the following files use `parts`:

* src/boot/boot.janet (e.g. https://github.com/janet-lang/janet/blob/master/src/boot/boot.janet#L1111 -- though it is `def`ed 5 times total)
* tools/gendoc.janet (e.g. https://github.com/janet-lang/janet/blob/master/tools/gendoc.janet#L105)
* src/core/array.c ([in the docs for `array/concat`](https://github.com/janet-lang/janet/blob/master/src/core/array.c#L346-L349))
* src/core/corelib.c ([in the doc params for `string`](https://github.com/janet-lang/janet/blob/master/src/core/corelib.c#L555))
* src/core/string.c ([in `cfun_string_join`](https://github.com/janet-lang/janet/blob/master/src/core/string.c#L432))

If you don't mind browsing how it's used in those places, perhaps it might factor into a leaning as to what to do for the current case.

My own sense is that `parts` is used less than `xs` (I did a similar search) and I think `xs` might be more familiar for some folks.

**Comment by andrewchambers** [comment]
xs is the plural of x afaik. x is just a generic variable.

**Comment by sogaiu** [comment]
Yes, that has been my understanding too.

**Comment by uvtc** [comment]
Thanks, @sogaiu . Since "parts" doesn't really convey any extra meaning here, I changed it to `xs`.

**Pull request merged**
