### PR TITLE
Add butlast function

### PR DESCRIPTION
**Pull request by skuzzymiglet**
butlast returns an array of all elements except the last. It works on empty arrays. Similar to Clojure's

### CODE REVIEW

**Comment by skuzzymiglet** [comment]
Should this function preserve the tuple/array distinction?

**Comment by subsetpark** [comment]
@skuzzymiglet i think as long as it relies on arrays to work, it shouldn’t automatically convert back to tuple for you. If there were some alternative implementations specific to tuples that might be a different story.

**Comment by andrewchambers** [comment]
I think we should make a semi official 'extended/supplemental core' library designed to be imported with 'use. The idea being that most things that want to be in core must first go through there.

**Comment by bakpakin** [comment]
Nothing wrong with his function in general, but not sure it should go into the core (just because Clojure has it in the core doesn't always mean we should too). I agree with Andrew that this would be better as a function in a library.

**Pull request closed without merging**
