### PR TITLE
Improve documentation on subprocess API

### PR DESCRIPTION
**Pull request by amano-kenji**
It closes https://github.com/janet-lang/janet/issues/1386

### CODE REVIEW

**Comment by amano-kenji** [comment]
By the way, `os/proc-kill` actually calls `os/proc-wait`. It is just the C version of `os/proc-wait`.

I changed the documentation. Now, `os/proc-kill` doesn't mention it returns the exit code if wait is truthy.

**Comment by amano-kenji** [comment]
I found a little problem. This is os/proc-wait

```c
#ifdef JANET_EV
    os_proc_wait_impl(proc);
    return janet_wrap_nil();
#else
    return os_proc_wait_impl(proc);
#endif
```

Although ev is enabled, it still returns the exit code. Somehow, `janet_wrap_nil` returns exit code.....

I just tested this code.

```
(def proc (os/spawn ["sleep" "10000000"] :p))

(ev/sleep 1)

(printf "exit code %n" (os/proc-kill proc true :term))
```

The exit code was returned from `os/proc-kill` although ev was enabled. Thus, I'm going to revert the commit.

**Comment by amano-kenji** [comment]
To avoid mentioning `os/proc-wait` in `os/proc-kill` without causing confusion, janet would need to ship with a document about subprocess management, and subprocess functions will need to refer users to the document for details.

Right now, janet doesn't ship with `info janet` or anything like that.

Emacs documentation is heavily hyperlinked. I want doc function to refer to relevant documentation. Right now, it is `os/proc-wait`.

**Comment by sogaiu** [comment]
As I've mentioned elsewhere, I think the expectation with Janet is to read the website docs along with the docstrings (though the docstrings live among the website docs as well (for most releases)).

I'll give an example of something that isn't really in the docstrings nor does it seem practical to put it in some docstring.  How long-strings work has no obvious place in docstrings, nor does syntax for buffers, etc.  If we start to think about it, we may come up with other sorts of examples as well, but I'm not going to go into that at this time.  A point of this paragraph is that docstrings are not practical as the sole method of understanding a programming language.  Having something else as well is way more helpful than not.

The website is available to many users over the Internet and it also exists in a repository that can be cloned if one wants to view those docs locally [1].

Thus I disagree with:

> To avoid mentioning os/proc-wait in os/proc-kill without causing confusion, janet would need to ship with a document about subprocess management, and subprocess functions will need to refer users to the document for details.

I believe we're in the process of [working on subprocess management docs for the website](https://github.com/janet-lang/janet-lang.org/issues/215).  I think it would be better to figure out what goes there before settling on what goes in this PR.

Having said that, I think clarifying the information in this PR could be helpful in formulating subprocess management documentation.

---

[1] Possibly that's a bit more challenging for Windows folks because of the use of `make`, though I think it may still be possible with a bit of work.  If the current state is a significant issue, perhaps a PR to try to address that would be accepted.

**Comment by amano-kenji** [comment]
The fact that janet doesn't document thoroughly doesn't mean it's the right way. The fact that something has bone done in a certain way doesn't mean it can't be improved.

Emacs has complete hyperlinked documentation online and offline.

If I look up function documentation in emacs, I get hyperlinks to relevant details. If I press Ctrl+h K, then I am transferred to info manual section on the function.

Whatever we end up doing, users reading `(doc os/xxx)` should be referred to relevant documentation. Referring users to online documentation is not great.

**Comment by sogaiu** [comment]
I agree I was mistaken about `os/proc-wait`.

However:

> Somehow, janet_wrap_nil returns exit code.....

This is also incorrect.

What appears to happen is that `os_proc_wait_impl(proc);` does not end up returning in this case, it does not appear to get beyond [this line](https://github.com/janet-lang/janet/blob/431ecd3d1a4caabc66b62f63c2f83ece2f74e9f9/src/core/os.c#L598):

```c
    janet_await();
```

I think you need to read what I wrote more carefully though.

[I wrote above](https://github.com/janet-lang/janet/pull/1394#issuecomment-1932196896):

> What I'm doing is to execute small samples of Janet code as well as compare the prose with what I see in the C implementations. I may also end up tracing execution with gdb / rr at some point.

In this case I had not yet traced execution yet due to time constraints, but I think the `os/proc-wait` discussion shows that I should change that "may" to a "will".  It's good that you caught the mistaken conclusion.  Thanks.

At present I intend to go through the docstrings in this PR with the slightly amended (`s/may/will/`) plan in hand to understand them well enough to inform drafting a page on subprocess management.  Once the page on subprocess management has taken shape I think it makes sense to revisit the docstrings, possibly to be followed with some iterating over both.

**Comment by sogaiu** [comment]
> The fact that janet API doesn't document things thoroughly doesn't mean it's the right way. The fact that something has bone done in a certain way doesn't mean it can't be improved.

I don't disagree with this, but I don't think there is anyone who is stepping up to do this yet.

I am working with things as they are, I likely won't object to adjusting if things change, but I doubt they will change any time soon.

It's not soley a matter of making the change either, the new arrangement should also match the needs of the main maintainer.  It has to be doable for him to look after in the long term because the rest of us come and go.

**Comment by amano-kenji** [comment]
Even if the website has a section on subprocess management, there is no guarantee that people will read it or start there.

Many people may start using functions directly. Then, I can imagine them coming to janet matrix channel to ask about `os/proc-wait` and `os/proc-kill` because `(doc os/proc-kill)` doesn't mention peculiarities of `os/proc-wait` such as not being able to wait twice on a process and `os/proc-wait` finishing in the background even if it is cancelled by `ev/with-deadline`.

I had to reverse-engineer those details for hours.... If I'm stuck in my rut after starting with `os/spawn`, it's very likely that the subprocess section on the website will not occur to my mind. So, even if the section is on the website, I'm still likely to bang my head on the wall for hours and be stressed out.

That's what usually has happened to me even if there is documentation because janet internal doc doesn't refer people to background information.

So, janet internal doc needs to refer people to relevant documentation. Hyperlinks make documentation cohesive. If you skip referring people to documentation, then documentation loses cohesiveness.

Documents need to link to each other.

If someone has to reverse-engineer something or wonder where the relevant details are, then the documentation is not good enough. Emacs solved that issue with hyperlinked documentation.

**Comment by sogaiu** [comment]
As I wrote above, I suggest you put thoughts about offline documentation in another issue.

[As bakpakin has mentioned elsewhere, this is not a chatroom.  It is an issue tracker.](https://github.com/janet-lang/janet/issues/1386#issuecomment-1922655204)

Please try to stay on the topic for each issue.  Not doing so too much makes it difficult for current readers but also future readers who may be trying to investigate an issue or understand the context of some decision.  You are causing clutter that may adversely affect the time, energy, and resources of people trying to improve Janet (which I also believe you are genuinely trying to do).

**Comment by amano-kenji** [comment]
Okay.

**Comment by sogaiu** [comment]
Thank you for your cooperation, I appreciate it!

**Pull request merged**
