### PR TITLE
Take and drop

### PR DESCRIPTION
**Pull request by curist**
Cont #154 
Did something stupid to my fork branch.

### CODE REVIEW

**Comment by curist** [comment]
I checked how `partition` is implemented, but I believe using `slice` will always get us a new array?
And, you probably already well aware of this, this PR will change the behaviors for `take-while` and friends, thus is a breaking change.

**Comment by bakpakin** [comment]
Yes, `*/slice` will always create a new array/string/buffer/etc, even if nothing was cut-off. I don't think this is a big deal. The changes to take-while, etc. also look acceptable.

**Comment by curist** [comment]
there is one thing that I would love to have your input
```
(assert (deep= (take-until |(= $ 115) "books") "book") "take-until 6")
```
`find-index` function uses `(get ind i)`, and for string, that get us the char code of the character; is there a better way to do this? `((string/bytes "s") 0)` won't look too great imo, but probably better than that literal `115` right there?

**Comment by bakpakin** [comment]
You can index into strings, buffers, keywords, and symbols directly to get at the contained bytes.

```clojure
(assert (deep= (take-until |(= $ ("s" 0)) "books") "book") "take-until 6")
```

**Comment by curist** [comment]
Cool, didn't know this trick!

**Pull request merged**
