### PR TITLE
Tweak and / or

### PR DESCRIPTION
**Pull request by primo-ppcg**
- Fixes the following error: `and` fails to return the last truthy value, if that value is `true`.
```janet
(and true 1 true)
```
Expected: `true`
Actual: `1`
- Changes naming conventions and formatting of `or` to match that of `and`.
- Recursively expands splices in both `and` and `or`. #1117 
- Updates test cases.

### CODE REVIEW

**Comment by bakpakin** [comment]
The handling of the splice code is wrong and useless - it can only handle splicing statically known arrays, which defeats the point of splice in the first place. For example:

```
(and ;(my-array-ctor))
```
expands to `my-array-ctor`, which is clearly wrong.

You cannot handle splice like this, the entire point of splice is that you don't know the number of parameters passed at compile time, and is likely something that can't even be determined. Also the compiler supports other handling of splice that this simple inspection-based macro implementation cannot handle. For example:

```
(+ (do (splice [1 2 3 4])))
```

Even though splice is inside `do`, it is expanded in. Admittedly this is non guaranteed behavior, but begs the question of why we are having special handling of splice in the `and` and `or` macros.

**Comment by primo-ppcg** [comment]
```janet
(and true 1 true)
```
still stands as an open bug.

Best of luck with your project.

**Comment by bakpakin** [comment]
fixed in 4cc4a9d38ba4bf9271f96a820decb64c33d61de5

**Comment by bakpakin** [comment]
Thank you for the bug report, that bug has been sitting in plain sight for a while - it mostly went unnoticed since it doesn't change behavior when logical macros are used as conditions.

The splice behavior though was already closed as "not a bug", so I won't merge that. The bug fix for `(and true 1 true)` would have been better received if it was not intertwined with "fixes" for behavior that was already closed as "not a bug" in #1117. And didn't itself have bugs. The better fix is much simpler and more correct in this case.

I did not respond during the week since I have a day job, so lately I have been doing most of my Janet work on the weekends.

**Comment by primo-ppcg** [comment]
I interpretted from your comments, specifically
> notably macros can do whatever they want the splice form

that the issue was closed as "will not fix" rather than "not a bug." I personally find the current behavior to be surprising, and I don't believe I'm the only one. That forms are passed to macros unevaluated, necessary in this case for short-circuiting behavior, does complicate the matter somewhat. Possibly more than is worth dealing with.

**Pull request closed without merging**
